AllCops:
  Exclude:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Include: ["app/controllers/*"]
  Max: 20
Metrics/AbcSize:
  Include: ["app/controllers/*"]
  Max: 30
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ['describe']

Metrics/Documentation:
  Enabled: false
Metrics/ClassAndModuleChildren:
  Enabled: false

Metrics/AlignHash:
  EnforcedColonStyle: key
Metrics/ExtraSpacing:
  AllowForAlignment: false
Metrics/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
