AllCops:
  Exclude:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
  DisplayCopNames: true

Layout/LineLength:
  Max: 120
Layout/MethodLength:
  Include: ["app/controllers/*"]
  Max: 20
Layout/AbcSize:
  Include: ["app/controllers/*"]
  Max: 30
Layout/ClassLength:
  Max: 150
Layout/BlockLength:
  ExcludedMethods: ['describe']

Layout/Documentation:
  Enabled: false
Layout/ClassAndModuleChildren:
  Enabled: false

Layout/AlignHash:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
